CICD: Upload Test Ouptut if Tests Are Failing.
If any of the automated tests are failing, upload the output from the
tests as an artifact to enable analysis of logs and output files.
Also remove running of the tests from the Ubuntu AppImage workflow, as
the same tests are already run for the regular Ubuntu build.

Signed-off-by: Michael Keller <github@ike.ch>

diff --git a/.github/workflows/linux-debian-generic.yml b/.github/workflows/linux-debian-generic.yml
--- a/.github/workflows/linux-debian-generic.yml
+++ b/.github/workflows/linux-debian-generic.yml
@@ -103,6 +103,21 @@ jobs:
         cd build/tests
         # xvfb-run --auto-servernum ./TestGitStorage -v2
         xvfb-run --auto-servernum make check
+        if [ $? -ne 0 ]; then
+          echo "Tests failed - adding the build output as artifacts"
+          exit 1
+        fi
+
+    - name: upload test artifacts
+      if: failure()
+      uses: actions/upload-artifact@v4
+      with:
+        name: test-output-${{ steps.version_number.outputs.version }}
+        path: |
+          build/tests/
+          !build/tests/CMakeFiles/
+          !build/tests/Test*
+          build/tests/Testing/
 
     - name: build subsurface-downloader
       run: |
